sonar.projectKey=dfsgotl-lenya_findex
sonar.organization=dfsgotl

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,**/.venv/**,data/**,tests/**,benchmarks/**
